flysystem:
    storages:
        storage.files:
            adapter: 'local'
            options:
                directory: '%env(resolve:FILE_PATH)%'
        storage.thumbnails:
            adapter: 'local'
            options:
                directory: '%env(resolve:THUMBNAIL_PATH)%'
        storage.mime:
            adapter: 'local'
            options:
                directory: '%env(resolve:THUMBNAIL_MIME)%'
