parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    Mimey\MimeTypes:
        class: 'Mimey\MimeTypes'
    Jenssegers\ImageHash\Implementations\PerceptualHash:
        class: 'Jenssegers\ImageHash\Implementations\PerceptualHash'
    Jenssegers\ImageHash\ImageHash:
        class: 'Jenssegers\ImageHash\ImageHash'
        arguments:
            - '@Jenssegers\ImageHash\Implementations\PerceptualHash'