parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $thumbnailSize: '%env(THUMBNAIL_SIZE)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    App\DataTransformer\:
        resource: '../src/DataTransformer/'
        tags: ['api_platform.data_transformer']
    Mimey\MimeTypes:
        class: 'Mimey\MimeTypes'
    Jenssegers\ImageHash\Implementations\PerceptualHash:
        class: 'Jenssegers\ImageHash\Implementations\PerceptualHash'
    Jenssegers\ImageHash\Implementations\AverageHash:
        class: 'Jenssegers\ImageHash\Implementations\AverageHash'
    Jenssegers\ImageHash\ImageHash:
        class: 'Jenssegers\ImageHash\ImageHash'
        arguments:
            - '@Jenssegers\ImageHash\Implementations\AverageHash'